import { useEffect, useState } from 'react';
import { testimonialVideoApi } from './testimonialVideoApi';

const initialForm = { title: '', personName: '', description: '', displayOrder: 0 };
const duration = (seconds) => `${Math.floor(Number(seconds || 0) / 60)}:${String(Math.round(Number(seconds || 0)) % 60).padStart(2, '0')}`;
const readMetadata = (file) => new Promise((resolve, reject) => {
  const video = document.createElement('video'); const url = URL.createObjectURL(file); video.preload = 'metadata';
  video.onloadedmetadata = () => { const value = { durationSeconds: video.duration, width: video.videoWidth, height: video.videoHeight }; URL.revokeObjectURL(url); Number.isFinite(value.durationSeconds) && value.durationSeconds > 0 ? resolve(value) : reject(new Error('Could not read this video.')); };
  video.onerror = () => { URL.revokeObjectURL(url); reject(new Error('Choose a browser-compatible MP4 video.')); }; video.src = url;
});

export default function TestimonialVideos({ onToast }) {
  const [videos, setVideos] = useState([]); const [form, setForm] = useState(initialForm); const [file, setFile] = useState(null); const [metadata, setMetadata] = useState(null);
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [progress, setProgress] = useState(0); const [error, setError] = useState(''); const [preview, setPreview] = useState(null);
  async function load({ silent = false } = {}) { if (!silent) setLoading(true); try { const data = await testimonialVideoApi.list(); setVideos(data.videos || []); setError(''); } catch (value) { setError(value.message); } finally { if (!silent) setLoading(false); } }
  useEffect(() => { load(); }, []);
  const processing = videos.some((video) => ['uploading', 'processing'].includes(video.status));
  useEffect(() => { if (!processing) return undefined; const timer = window.setInterval(() => load({ silent: true }), 8000); return () => window.clearInterval(timer); }, [processing]);
  async function chooseFile(event) { const value = event.target.files?.[0] || null; setFile(value); setMetadata(null); setError(''); if (!value) return; if (value.type && value.type !== 'video/mp4') return setError('Only MP4 videos are supported.'); try { setMetadata(await readMetadata(value)); } catch (metadataError) { setError(metadataError.message); } }
  async function submit(event) { event.preventDefault(); if (!file || !metadata || !form.title.trim()) return setError('Add a title and choose a valid MP4 video.'); const formElement = event.currentTarget; setSubmitting(true); setProgress(0); setError(''); try { const created = await testimonialVideoApi.createUpload({ ...form, mimeType: 'video/mp4', sizeBytes: file.size, fileName: file.name }); await testimonialVideoApi.uploadFile(created.uploadUrl, file, setProgress); await testimonialVideoApi.complete(created.video.id, metadata); setForm(initialForm); setFile(null); setMetadata(null); setProgress(0); formElement.reset(); onToast?.('Story uploaded. Cloudflare is preparing the video.'); await load(); } catch (value) { setError(value.message); } finally { setSubmitting(false); } }
  async function toggle(video) { try { if (video.status === 'published') await testimonialVideoApi.disable(video.id); else if (video.status === 'disabled') await testimonialVideoApi.enable(video.id); else await testimonialVideoApi.publish(video.id); onToast?.(video.status === 'published' ? 'Story hidden from the app' : 'Story published to the app'); await load(); } catch (value) { setError(value.message); } }
  async function openPreview(video) { try { setPreview({ ...video, ...(await testimonialVideoApi.playback(video.id)) }); } catch (value) { setError(value.message); } }
  return <div className="stories-page"><section className="stories-hero"><div><span className="eyebrow">CUSTOMER PROOF</span><h2>Real stories, ready to inspire.</h2><p>Upload customer journeys to Cloudflare Stream and control what appears inside the personalized plan.</p></div><div className="stories-hero-count"><strong>{videos.filter((item) => item.status === 'published').length}</strong><span>live stories</span></div></section>
    {error ? <div className="error-banner"><strong>Story operation failed.</strong><span>{error}</span></div> : null}<section className="stories-workspace"><aside className="panel story-upload-card"><div className="reel-section-head"><div><span className="step">01</span><div><small>CREATE</small><h3>Upload a customer story</h3></div></div></div><form onSubmit={submit}>
      <label className="video-field"><span>Card title</span><input maxLength="160" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="My journey with Muditam"/></label><label className="video-field"><span>Person name <em>optional</em></span><input maxLength="120" value={form.personName} onChange={(event) => setForm({ ...form, personName: event.target.value })} placeholder="Meena Rao"/></label><label className="video-field"><span>Description <em>optional</em></span><textarea maxLength="1000" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="A short line shown with the story"/></label><label className="video-field"><span>Display order</span><input type="number" value={form.displayOrder} onChange={(event) => setForm({ ...form, displayOrder: Number(event.target.value) })}/></label>
      <label className="reel-drop"><input type="file" accept="video/mp4,.mp4" onChange={chooseFile}/><span className="reel-drop-icon">＋</span><b>{file?.name || 'Choose customer story MP4'}</b><small>{metadata ? `${metadata.width}×${metadata.height} · ${duration(metadata.durationSeconds)}` : 'Portrait video recommended · max 200 MB'}</small></label><div className="video-upload-progress"><i style={{ width: `${progress}%` }}/></div><button className="save-button video-submit" disabled={submitting || !metadata || !form.title.trim()}>{submitting ? `Uploading ${progress}%` : 'Upload story'} <b>→</b></button></form></aside>
      <section className="panel story-library-card"><div className="reel-section-head"><div><span className="step">02</span><div><small>PERSONALIZED PLAN</small><h3>Story library</h3></div></div><button className="secondary-button" onClick={() => load()} disabled={loading}>Refresh</button></div><div className="story-library-list">{loading ? [...Array(4)].map((_, index) => <div className="reel-row-skeleton" key={index}/>) : videos.map((video) => <article className="story-library-row" key={video.id}><button className="story-thumb" style={video.thumbnailUrl ? { backgroundImage: `linear-gradient(#0003,#0003),url(${video.thumbnailUrl})` } : undefined} disabled={!['ready','published','disabled'].includes(video.status)} onClick={() => openPreview(video)}><span>▶</span></button><div className="story-row-copy"><div><h4>{video.title}</h4><span className={`reel-status ${video.status}`}>{video.status}{video.status === 'processing' && video.processingPercent ? ` ${Math.round(video.processingPercent)}%` : ''}</span></div><p>{video.personName || 'Customer story'} · {duration(video.durationSeconds)}</p><small>{video.errorMessage || video.description || 'No description added'}</small></div><div className="story-order">ORDER<strong>{video.displayOrder}</strong></div><div className="reel-row-controls"><label className={`reel-switch ${video.status === 'published' ? 'on' : ''}`} title={video.status === 'published' ? 'Hide story' : 'Publish story'}><input type="checkbox" checked={video.status === 'published'} disabled={!['ready','published','disabled'].includes(video.status)} onChange={() => toggle(video)}/><i/></label><button disabled={!['ready','published','disabled'].includes(video.status)} onClick={() => openPreview(video)}>Preview</button></div></article>)}{!loading && !videos.length ? <div className="reel-empty"><span>▶</span><strong>No customer stories yet</strong><p>Your first upload will appear here.</p></div> : null}</div></section></section>
    {preview ? <div className="video-preview-backdrop" onClick={() => setPreview(null)}><section className="reel-preview-modal" onClick={(event) => event.stopPropagation()}><div className="video-preview-header"><div><small>CLOUDFLARE STREAM PREVIEW</small><h2>{preview.title}</h2></div><button className="video-preview-close" onClick={() => setPreview(null)}>×</button></div>{preview.previewUrl ? <iframe title={preview.title} src={preview.previewUrl} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/> : <video className="video-preview-player" controls autoPlay playsInline src={preview.playbackUrl}/>}</section></div> : null}</div>;
}
